import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/app/utilsFunctions/Providers/sessionProvider";
import { auth } from "@/auth";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Favicon from "/public/favicon.ico"
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Torus9x",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],

};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>{" "}
        <ToastContainer/>
      </body>
    </html>
  );
}
