import React from "react";
import { Providers } from "@/app/utilsFunctions/Providers/NextUIProvider";

import "./globals.css";
import NextThemeProvider from "@/app/utilsFunctions/Providers/NextThemesProvider";
import { Inter } from "next/font/google";

import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Torus 9X App",
  description: "Generated by create next app",
};
type Realm = {
  id: string;
  name: string;
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <NextThemeProvider>{children}</NextThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
