import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Favicon from "/public/favicon.ico"
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider, ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Torus9x",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextUIProvider>
        <ThemeProvider>
      <body className={inter.className}>
        {children}
      <ToastContainer/>
        </body>
        </ThemeProvider>
        </NextUIProvider>
    </html>
  );
}
